version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ./app:/var/www/html
    environment:
      APP_DEBUG: true
      APP_ENV: local
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-webserver
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/html
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge